HOST:
  GLOBAL: 'https://toyoko.backlog.jp'
  IP: 'https://toyoko-ip.backlog.com'

API_KEY:
  GLOBAL: ''
  IP: ''

PROCESSING_PROJECT_KEY:
  - [ProjectKey]

PROCESSING_TERM:
  START_DATE: '2018-10-01'
  END_DATE: '2018-10-31'

PROCESSING_ISSUE_TYPE_NAME: 'タスク（保守）'